version: '3'

services:
  opensovs-db:
    image: postgres:latest
    container_name: opensovs-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=opensovs
